[editor]
mouse = false
color-modes = true
cursorline = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "-- INSERT --"
mode.select = "-- SELECT --"